name: intellij-idea-community # you probably want to 'snapcraft register <name>'
version: '2017.2.5'
summary: Java, Scala, Kotlin IDE for JVM and Android development
description: |
  Every aspect of IntelliJ IDEA is specifically
  designed to maximize developer productivity.
  Together, powerful static code analysis and
  ergonomic design make development not only
  productive but also an enjoyable experience.
grade: stable
confinement: classic
architectures:
  - amd64

apps:
  intellij-idea-community:
    command: bin/idea.sh
    desktop: intellij-idea-community.desktop

parts:
  desktop:
    after:
      - intellij-idea-community
    plugin: dump
    source: .
    prime:
      - intellij-idea-community.desktop
  intellij-idea-community:
    plugin: dump
    source: https://download.jetbrains.com/idea/ideaIC-$SNAPCRAFT_PROJECT_VERSION.tar.gz

